name: Auto Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Проверяем репозиторий
        uses: actions/checkout@v3

      - name: Подключаемся к серверу и деплоим
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            # Экспортируем переменные окружения
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export PORT=${{ secrets.PORT }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export SMTP_SERVICE_NAME=${{ secrets.SMTP_SERVICE_NAME }}
            export SMTP_USER=${{ secrets.SMTP_USER }}
            export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            
            # Переходим в директорию проекта
            cd /var/www/auth_service

            # Обновляем репозиторий и устанавливаем зависимости
            git pull origin main
            npm install
            npm run build

            # Перезапускаем приложение через pm2
            pm2 restart auth_service
